Adds missing dependency on `mime`
As mentioned [here](https://yarnpkg.com/lang/en/docs/workspaces/#toc-limitations-caveats) this kind of issue can be hard to detect, since the package is installed in the Yarn Workspace by another package.

Fixes
```
success write out page data — 0.003 s
success write out redirect data — 0.000 s
success onPostBootstrap — 0.000 s

info bootstrap finished - 2.16 s

error UNHANDLED REJECTION

  TypeError: mime.getType is not a function

  - create-fake-file-node.js:42 exports.createFileNode
    [site]/[gatsby-mdx]/utils/create-fake-file-node.js:42:28

  - mdx-loader.js:102 Object.module.exports
    [site]/[gatsby-mdx]/loaders/mdx-loader.js:102:22

  - LoaderRunner.js:119 LOADER_EXECUTION
    [site]/[loader-runner]/lib/LoaderRunner.js:119:14

  - LoaderRunner.js:120 runSyncOrAsync
    [site]/[loader-runner]/lib/LoaderRunner.js:120:4

  - LoaderRunner.js:229 iterateNormalLoaders
    [site]/[loader-runner]/lib/LoaderRunner.js:229:2

  - LoaderRunner.js:202 Array.<anonymous>
    [site]/[loader-runner]/lib/LoaderRunner.js:202:4

  - CachedInputFileSystem.js:43 Storage.finished
    [site]/[enhanced-resolve]/lib/CachedInputFileSystem.js:43:16

  - CachedInputFileSystem.js:79 provider
    [site]/[enhanced-resolve]/lib/CachedInputFileSystem.js:79:9

  - graceful-fs.js:78
    [site]/[graceful-fs]/graceful-fs.js:78:16

  - read_file_context.js:53 FSReqWrap.readFileAfterClose [as oncomplete]
    internal/fs/read_file_context.js:53:3

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```